name: CI / Deploy to GHCR

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  call-ghcr-workflow:
    uses: offensive-vk/Assets/.github/workflows/ghcr.yml@master
    with:
      author: "Vedansh"
      title: "auto-contributions"
      description: "Github Action that generates the Contributions, Coding Style, Most Used Languages of a Github User in SVG Format."
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}