name: CI / Generate Contribution

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'Username'
        required: true
        type: string
        default: 'offensive-vk'

jobs:
  pattern:
    name: Generate Pattern
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: offensive-vk/auto-contributions@master
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GH_TOKEN || secrets.BOT_TOKEN }}
          USERNAME: ${{ github.event.inputs.user || 'offensive-vk' }}

      - name: Import GPG Key
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true
          trust_level: 5

      - name: Verify GPG Key
        run: |
          gpg --list-secret-keys --keyid-format LONG
          git config --global --list

      - name: Commit & Push
        continue-on-error: true
        run: |
          git config user.email "TheHamsterBot@outlook.com"
          git config user.name "TheHamsterBot"
          git add -A .
          git commit -m ":bowtie: Updated The Contributions Patterns.


          Signed-off-by: Hamster [bot] <TheHamsterBot@outlook.com>
          Co-Authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          git push

      - name: Complete Job
        run: echo "Job Finished ! - Signing Off."
